<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href=" https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <style>
        body{
            font-family: sans-serif;
        }
    </style>
</head>
<body>
    <div class="container" > -->
        <!-- L'attribut enctype spécifie comment les données du formulaire doivent être encodées avant d'être 
    envoyés au serveur lorsque le formulaire est soumis.Cet attribut est particulièrement important lorsque vous avez des champs de formulaire de type 
"file" .

Lorsque vous définissez `enctype="multipart/form-data"`, cela signifie que les données du formulaire seront encodés sous la forme d'un contenu binaire multipart. Ce type d'encodage est utilisé pour les formulaires contenant des champs de téléchargement de fichiers, car il permet de transférer des fichiers binaires, tels que les images, les viséos, etc..., en plus de données de texte.--> 

     <!-- <form action="server.php" method="post" enctype="multipart/form-data">

            <div class="mb-3">
                <input type="hidden" name="MAX_FILE_SIZE " value="3000000">
                <label for="file">Importez un fichier</label> <br> <br>
                <input type="file" class="form-control" name="photo_profile"  id="file"><br>
                <button type="submit" class="btn btn-primary" name="submit">Submit</button>
            </div>
        </form>
            <a href="./download.php?file=img-upload-1693324977.png" name="file">Télécherger l'image</a>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    </div>
</body>
</html> -->